---
title: "In-class zonal and other stuff"
output: html_notebook
---

```{r}
library(tidyverse)
library(terra)
library(tidyterra)
library(sf)
library(mapview)

```

Read NLCD for northeast ohio

```{r}

neoh_lulc <- terra::rast("../data/ohio/neoh_nlcd.tif")

# summary
terra::summary(neoh_lulc)


# plot it
terra::plot(neoh_lulc)

```
Vector data
```{r}
# using terra vector classes to make later operations easier
# project to the crs of the raster so we don't need to resample raster (which takes forever)
neoh_counties <- vect("../data/ohio/neoh_counties.gpkg") %>%
  terra::project(., crs(neoh_lulc))

oh_tracts <- vect("../data/ohio/oh_tracts_2020.gpkg") %>%
  terra::project(., crs(neoh_lulc))

```


Test some zonal activities
```{r}

test <- terra::zonal(neoh_lulc, neoh_counties)


```

What do we get?

Let's try something a bit more intelligent
```{r}
values <- extract(neoh_lulc, neoh_counties)
```

What do we get?

```{r}
values %>% group_by(ID, `NLCD Land Cover Class`) %>%
  summarise(ncells = n())
```



look up table to figure out which counties are which

eventually join back to the vector




Later we'll do pivot longer and pivot wider