---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(sf)
library(terra)
library(tmap)
library(spData) # new package - you'll likely need to install
library(tidyverse)
```



```{r}

sa <- read_sf("../data/static_mapping/oh_counties.gpkg") %>%
  dplyr::filter(NAME %in% c("Portage", "Summit"))


allohio  <- read_sf("../data/static_mapping/oh_counties.gpkg")

oh_region = st_bbox(sa) %>%
  st_as_sfc()
```


```{r}
myras <- rast("../data/static_mapping/neoh_dem.tif") %>% 
  terra::project(., "EPSG:4269") %>%
  terra::crop(sa)

```

```{r}

parks <- read_sf("../data/static_mapping/oh_parks.gpkg")

parks.sa <- parks %>% st_transform(st_crs(sa)) %>%
  st_intersection(., sa)


oh_height_map = tm_shape(myras, bbox = oh_region) +
  tm_raster(col.scale = tm_scale_continuous(values = "YlGn"),
            col.legend = tm_legend(position = c("left", "top"))) +
  tm_shape(sa) + tm_polygons(fill_alpha = .2) +
  tm_shape(parks.sa) + tm_polygons(fill = "FEATTYPE", fill_alpha = .5) +
  tm_scalebar(position = c("left", "bottom"))
```

```{r}
oh_map = tm_shape(allohio) + tm_polygons() + 
  tm_shape(oh_region) + tm_borders(lwd = 3) +
  tm_layout(bg.color = "lightblue") +
  tm_scalebar(position = c("left", "bottom"))
```

```{r}
library(grid)
norm_dim = function(obj){
    bbox = st_bbox(obj)
    width = bbox[["xmax"]] - bbox[["xmin"]]
    height = bbox[["ymax"]] - bbox[["ymin"]]
    w = width / max(width, height)
    h = height / max(width, height)
    return(unit(c(w, h), "snpc"))
}
main_dim = norm_dim(oh_region)
ins_dim = norm_dim(sa)
```

```{r}
main_vp = viewport(width = main_dim[1], height = main_dim[2])
```


```{r}
ins_vp = viewport(width = ins_dim[1] * 0.6, height = ins_dim[2] * 0.6,
                  x = unit(1, "npc") - unit(0.6, "cm"), y = unit(0.1, "npc"),
                  just = c("right", "bottom"))
```

```{r}
grid.newpage()
print(oh_height_map, vp = main_vp)
pushViewport(main_vp)
print(oh_map, vp = ins_vp)
```

It's ugly and needs work to fix the layout, but this gives you an idea of how to put it all together